chore: Disable push validation hook for Crove fork
- Comment out branch protection for develop/master branches
- Allow direct push to own repository branches
- Useful for Git GUI clients that don't support --no-verify flag

diff --git a/bin/validate_push b/bin/validate_push
--- a/bin/validate_push
+++ b/bin/validate_push
@@ -1,13 +1,17 @@
 #!/bin/sh
 
 # script prevents pushing to develop and master by mistake
+# DISABLED FOR CROVE FORK - We can push directly to our own branches
 
-branch="$(git rev-parse --abbrev-ref HEAD)"
+# branch="$(git rev-parse --abbrev-ref HEAD)"
+# 
+# if [ "$branch" = "master" ]; then
+#   echo "You can't push directly to master branch"
+#   exit 1
+# elif [ "$branch" = "develop" ]; then
+#   echo "You can't push directly to develop branch"
+#   exit 1
+# fi
 
-if [ "$branch" = "master" ]; then
-  echo "You can't push directly to master branch"
-  exit 1
-elif [ "$branch" = "develop" ]; then
-  echo "You can't push directly to develop branch"
-  exit 1
-fi
+# Always allow push for Crove fork
+exit 0
